# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import math


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 900)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(-11, -1, 811, 901))
        self.widget.setStyleSheet(
            "QWidget#widget{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(139, "
            "171, 193, 255), stop:1 rgba(147, 211, 160, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(330, 10, 151, 51))
        self.label.setStyleSheet("font: 600 30pt \"Raleway\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(140, 60, 121, 31))
        self.label_2.setStyleSheet("font: 500 30pt \"Arial\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.text_sifrovani = QtWidgets.QTextEdit(parent=self.widget)
        self.text_sifrovani.setGeometry(QtCore.QRect(50, 100, 311, 81))
        self.text_sifrovani.setStyleSheet("QTextEdit{\n"
                                          "background-color:rgb(255, 255, 255);\n"
                                          "font: 18pt \"Raleway\"; background-color: white;\n"
                                          "color: black;\n"
                                          "border-radius: 15px;\n"
                                          "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                          "padding-left:5px;\n"
                                          "padding-top:5px;\n"
                                          "}\n"
                                          "\n"
                                          "QTextEdit:focus{\n"
                                          "border: 2px solid rgb(126, 145, 191);\n"
                                          "\n"
                                          "}\n"
                                          "")
        self.text_sifrovani.setObjectName("text_sifrovani")
        self.encrypt = QtWidgets.QPushButton(parent=self.widget)
        self.encrypt.setGeometry(QtCore.QRect(130, 330, 141, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encrypt.sizePolicy().hasHeightForWidth())
        self.encrypt.setSizePolicy(sizePolicy)
        self.encrypt.setStyleSheet("QPushButton#encrypt{\n"
                                   "background-color:rgba(166, 205, 255,0.5);\n"
                                   "font: 600 25pt \"Raleway\";\n"
                                   "border-radius: 15px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#encrypt:hover{\n"
                                   "background-color:rgb(126, 145, 191);\n"
                                   "font: 700 26pt \"Raleway\";\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#encrypt:pressed{\n"
                                   "font: 600 24pt \"Raleway\";\n"
                                   "}\n"
                                   "\n"
                                   "")
        self.encrypt.setObjectName("encrypt")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(50, 400, 311, 41))
        self.label_3.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_3.setObjectName("label_3")
        self.filtrText = QtWidgets.QTextEdit(parent=self.widget)
        self.filtrText.setGeometry(QtCore.QRect(50, 440, 311, 81))
        self.filtrText.setStyleSheet("QTextEdit{\n"
                                     "background-color:rgb(255, 255, 255);\n"
                                     "font: 18pt \"Raleway\"; background-color: white;\n"
                                     "color: black;\n"
                                     "border-radius: 15px;\n"
                                     "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                     "padding-left:5px;\n"
                                     "padding-top:5px;\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus{\n"
                                     "border: 2px solid rgb(126, 145, 191);\n"
                                     "\n"
                                     "}\n"
                                     "")
        self.filtrText.setReadOnly(True)
        self.filtrText.setAcceptRichText(False)
        self.filtrText.setObjectName("filtrText")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(50, 550, 311, 41))
        self.label_4.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_4.setObjectName("label_4")
        self.encryptedText = QtWidgets.QTextEdit(parent=self.widget)
        self.encryptedText.setGeometry(QtCore.QRect(50, 590, 311, 81))
        self.encryptedText.setStyleSheet("QTextEdit{\n"
                                         "background-color:rgb(255, 255, 255);\n"
                                         "font: 18pt \"Raleway\"; background-color: white;\n"
                                         "color: black;\n"
                                         "border-radius: 15px;\n"
                                         "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                         "padding-left:5px;\n"
                                         "padding-top:5px;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "border: 2px solid rgb(126, 145, 191);\n"
                                         "\n"
                                         "}\n"
                                         "")
        self.encryptedText.setReadOnly(True)
        self.encryptedText.setObjectName("encryptedText")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(380, 210, 71, 31))
        self.label_5.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(314, 234, 21, 31))
        self.label_6.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setGeometry(QtCore.QRect(496, 234, 21, 31))
        self.label_7.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.klicA = QtWidgets.QLineEdit(parent=self.widget)
        self.klicA.setGeometry(QtCore.QRect(295, 270, 60, 40))
        self.klicA.setStyleSheet("QLineEdit{\n"
                                 "background-color:rgb(255, 255, 255);\n"
                                 "font: 18pt \"Raleway\"; background-color: white;\n"
                                 "color: black;\n"
                                 "border-radius: 15px;\n"
                                 "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:focus{\n"
                                 "border: 2px solid rgb(126, 145, 191);\n"
                                 "\n"
                                 "}\n"
                                 "")
        self.klicA.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.klicA.setObjectName("klicA")
        self.klicB = QtWidgets.QLineEdit(parent=self.widget)
        self.klicB.setGeometry(QtCore.QRect(478, 270, 60, 40))
        self.klicB.setStyleSheet("QLineEdit{\n"
                                 "background-color:rgb(255, 255, 255);\n"
                                 "font: 18pt \"Raleway\"; background-color: white;\n"
                                 "color: black;\n"
                                 "border-radius: 15px;\n"
                                 "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:focus{\n"
                                 "border: 2px solid rgb(126, 145, 191);\n"
                                 "\n"
                                 "}\n"
                                 "")
        self.klicB.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.klicB.setObjectName("klicB")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(550, 60, 151, 31))
        self.label_8.setStyleSheet("font: 500 30pt \"Arial\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.text_desifrovani = QtWidgets.QTextEdit(parent=self.widget)
        self.text_desifrovani.setGeometry(QtCore.QRect(470, 100, 311, 81))
        self.text_desifrovani.setStyleSheet("QTextEdit{\n"
                                            "background-color:rgb(255, 255, 255);\n"
                                            "font: 18pt \"Raleway\"; background-color: white;\n"
                                            "color: black;\n"
                                            "border-radius: 15px;\n"
                                            "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                            "padding-left:5px;\n"
                                            "padding-top:5px;\n"
                                            "}\n"
                                            "\n"
                                            "QTextEdit:focus{\n"
                                            "border: 2px solid rgb(126, 145, 191);\n"
                                            "\n"
                                            "}\n"
                                            "")
        self.text_desifrovani.setObjectName("text_desifrovani")
        self.label_23 = QtWidgets.QLabel(parent=self.widget)
        self.label_23.setGeometry(QtCore.QRect(470, 400, 311, 41))
        self.label_23.setStyleSheet("font: 500 30pt \"Raleway\";")
        self.label_23.setObjectName("label_23")
        self.decryptedText = QtWidgets.QTextEdit(parent=self.widget)
        self.decryptedText.setGeometry(QtCore.QRect(470, 440, 311, 81))
        self.decryptedText.setStyleSheet("QTextEdit{\n"
                                         "background-color:rgb(255, 255, 255);\n"
                                         "font: 18pt \"Raleway\"; background-color: white;\n"
                                         "color: black;\n"
                                         "border-radius: 15px;\n"
                                         "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                         "padding-left:5px;\n"
                                         "padding-top:5px;\n"
                                         "}\n"
                                         "\n"
                                         "QTextEdit:focus{\n"
                                         "border: 2px solid rgb(126, 145, 191);\n"
                                         "\n"
                                         "}\n"
                                         "")
        self.decryptedText.setReadOnly(True)
        self.decryptedText.setObjectName("decryptedText")
        self.decrypt = QtWidgets.QPushButton(parent=self.widget)
        self.decrypt.setGeometry(QtCore.QRect(560, 330, 141, 51))
        self.decrypt.setStyleSheet("QPushButton#decrypt{\n"
                                   "background-color:rgba(166, 205, 255,0.5);\n"
                                   "font: 600 25pt \"Raleway\";\n"
                                   "border-radius: 15px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#decrypt:hover{\n"
                                   "background-color:rgb(126, 145, 191);\n"
                                   "font: 700 26pt \"Raleway\";\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#decrypt:pressed{\n"
                                   "font: 600 24pt \"Raleway\";\n"
                                   "}\n"
                                   "")
        self.decrypt.setObjectName("decrypt")
        self.abecedaText = QtWidgets.QLineEdit(parent=self.widget)
        self.abecedaText.setGeometry(QtCore.QRect(50, 740, 731, 51))
        self.abecedaText.setStyleSheet("QLineEdit{\n"
                                       "background-color:rgb(255, 255, 255);\n"
                                       "font: 18pt \"Raleway\"; background-color: white;\n"
                                       "color: black;\n"
                                       "border-radius: 15px;\n"
                                       "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                       "}\n"
                                       "\n"
                                       "QLineEdit:focus{\n"
                                       "border: 2px solid rgb(126, 145, 191);\n"
                                       "\n"
                                       "}\n"
                                       "")
        self.abecedaText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.abecedaText.setReadOnly(True)
        self.abecedaText.setObjectName("abecedaText")
        self.abecedaText_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.abecedaText_2.setGeometry(QtCore.QRect(50, 810, 731, 51))
        self.abecedaText_2.setStyleSheet("QLineEdit{\n"
                                         "background-color:rgb(255, 255, 255);\n"
                                         "font: 18pt \"Raleway\"; background-color: white;\n"
                                         "color: black;\n"
                                         "border-radius: 15px;\n"
                                         "border: 2px solid rgba(166, 205, 255,0.5);\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:focus{\n"
                                         "border: 2px solid rgb(126, 145, 191);\n"
                                         "\n"
                                         "}\n"
                                         "")
        self.abecedaText_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.abecedaText_2.setReadOnly(True)
        self.abecedaText_2.setObjectName("abecedaText_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Afinni sifra"))
        self.label.setText(_translate("Dialog", "Afinní šifra"))
        self.label_2.setText(_translate("Dialog", "Šifrování"))
        self.text_sifrovani.setPlaceholderText(_translate("Dialog", "Zadejte text k šifrování..."))
        self.encrypt.setText(_translate("Dialog", "Zašifrovat"))
        self.label_3.setText(_translate("Dialog", "Filtrovaný text"))
        self.label_4.setText(_translate("Dialog", "Zašifrovaný text"))
        self.label_5.setText(_translate("Dialog", "Klíče"))
        self.label_6.setText(_translate("Dialog", "a"))
        self.label_7.setText(_translate("Dialog", "b"))
        self.label_8.setText(_translate("Dialog", "Dešifrování"))
        self.text_desifrovani.setPlaceholderText(_translate("Dialog", "Zadejte text k dešifrování..."))
        self.label_23.setText(_translate("Dialog", "Dešifrovaný text"))
        self.decrypt.setText(_translate("Dialog", "Dešifrovat"))
        self.encrypt.clicked.connect(self.zasifrovat_text)
        self.decrypt.clicked.connect(self.desifrovat_text)

    def zasifrovat_text(self):
        text = self.text_sifrovani.toPlainText()
        a_text = self.klicA.text()
        b_text = self.klicB.text()

        if not a_text.isdigit() or not b_text.isdigit():
            self.encryptedText.setText("Klíče musí být celá čísla.")
            return

        a = int(a_text)
        b = int(b_text)

        if not is_coprime_to_36(a):
            self.encryptedText.setText("Klíč 'a' není nesoudělný s číslem 36.")
            return

        bezDia = remove_diacritics(text)
        zasifrovane = encrypt(bezDia, a, b)

        if zasifrovane is not None:
            self.filtrText.setText(bezDia)
            self.encryptedText.setText(zasifrovane)

            modified_alphabet = ""
            modified_alphabet2 = ""
            oddelovac = " "
            for char in abeceda:
                modified_alphabet2 += char
                modified_alphabet2 += oddelovac

            for char in abeceda:
                index = abeceda.index(char)
                cipher = (a * index + b) % 36
                new_char = abeceda[cipher]
                modified_alphabet += new_char
                modified_alphabet += oddelovac

            self.abecedaText.setText(modified_alphabet2)
            self.abecedaText_2.setText(modified_alphabet)
        else:
            self.encryptedText.setText("Zadali jste neplatný klíč.")

    def desifrovat_text(self):
        text = self.text_desifrovani.toPlainText()
        a_text = self.klicA.text()
        b_text = self.klicB.text()

        if not a_text.isdigit() or not b_text.isdigit():
            self.decryptedText.setText("Klíče musí být celá čísla.")
            return

        a = int(a_text)
        b = int(b_text)

        if not is_coprime_to_36(a):
            self.decryptedText.setText("Klíč 'a' není nesoudělný s číslem 36.")
            return

        desifrovane = decrypt(text, a, b)

        if desifrovane is not None:
            self.decryptedText.setText(desifrovane)
        else:
            self.decryptedText.setText("Zadali jste neplatný klíč.")


# MOJE FUNKCE
abeceda = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"


def remove_diacritics(text):
    diacritics = ["Ě", "Š", "Č", "Ř", "Ž", "Ý", "Á", "Í", "É", "Ů", "Ú", "Ť", "Ď", "Ó", "Ň"]
    without_diacritics = ["E", "S", "C", "R", "Z", "Y", "A", "I", "E", "U", "U", "T", "D", "O", "N"]

    text = text.replace(" ", "XMEZERAX")
    result = ""
    text = text.upper()

    for char in text:
        if char in diacritics:
            index = diacritics.index(char)
            result += without_diacritics[index]
        elif char in abeceda:
            result += char

    return result


def is_coprime_to_36(a):
    return math.gcd(a, 36) == 1


def inverse(a):
    return pow(a, -1, 36)


def encrypt(text, a, b):
    if is_coprime_to_36(a):
        text = remove_diacritics(text)
        encrypted_text = ""
        i = 0

        for char in text:
            index = abeceda.index(char)
            cipher = (a * index + b) % 36
            new_char = abeceda[cipher]
            encrypted_text += new_char
            i += 1

            if i % 5 == 0:
                encrypted_text += " "

        return encrypted_text
    else:
        return None


def decrypt(text, a, b):
    abeceda = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    if is_coprime_to_36(a):
        text = text.replace(" ", "")

        decrypted_text = ""
        a_inverse = inverse(a)

        for char in text:
            index = abeceda.index(char)
            cipher = (index - b) * a_inverse % 36
            new_char = abeceda[cipher]
            decrypted_text += new_char

        decrypted_text = decrypted_text.replace("XMEZERAX", " ")
        return decrypted_text
    else:
        return None


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
